### ISSUE TITLE
Review with Peak (Feb21)

### ISSUE THREAD

**Issue by readywater** [Mulligan-Fund/grant-calculator#22]
PRE meeting knocklist
- [x] Grantmaker results page
- [ ] Is the salary list working?
- [ ] Registration (need to be able to create new accounts)
- [ ] About and contact pages
- [ ] Text on results pages for grantseeker (provided in issue #17) and grantmaker (to be provided by PEAK)
- [ ] Some UI fixes (e.g., text for some items on grantmaker page run into each other - -
 Publish/Release/Publicize RFP  
Contributo)
- [ ] I think it would be good to have a feedback mechanism even in the beta release

**Comment by readywater** [comment]
Participants
Peak: Michelle, Nicki, Melissa
Mull/NA: Dahna, Andrew

**Notes**
- Aligning language, stages of grants
- Conference, March 19 + 21 -> Orlando
- Tools under the epicenter
- Benchmarking library -> Effective Practice Improvements
- - Six Surveys that ask people how they do their practices. For each survey, we create a series of action guides; 1-1 ask them how they should be doing it. -> Match to resources + providing best practices
- - Application, Reporting/Monitoring, Compliance, etc.
- - Nicki will send to Dahna
- Quick gratification provides a strong value for this
**TODO**
- Dahna: Google docs
- Peak: Send 4-5 Grantmaker testers

**ISSUES**
- [ ] Separation between grant maker and grant seeker view
- [ ] Text Overrun on Grant Maker
- [ ] Monitoring and planning components of the grant journey
- [ ] Hint text for Team page?
- [ ] Conditional display of information depending on past response (Enhancement)
- [ ] Hone in on the calculation for Grantmaker Grant Seeker estimates
- [ ] Get Netgrant.org 
- [ ] Add "Top 10 ways to improve" for Grant Calc

**Comment by dahnag** [comment]
All of these items have been divided into individual issues.
